spring:
  sql:
    init:
      mode: embedded

  datasource:
    url: jdbc:postgresql://localhost:5432/utm
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.bos.usertaskmanager.model

  application:
    name: UserTaskManager

server:
  port: 8080
