spring:
  main:
    web-application-type: servlet
  sql:
    init:
      mode: embedded

  datasource:
    url: jdbc:postgresql://localhost:5432/utm
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.bos.usertaskmanager.model

server:
  port: 8080

logging:
  level:
    root: DEBUG
    org.springframework: DEBUG
    com.bos.usertaskmanager: DEBUG
    graphql: DEBUG

graphql:
  schema:
    locations: classpath:graphql/schema.graphqls
  servlet:
    enabled: true
    mapping: /graphql
  playground:
    enabled: true
    endpoint: /playground
  graphiql:
    enabled: true
    endpoint: /graphiql

management:
  endpoints:
    web:
      exposure:
        include: "*"
