spring:
  application:
    name: usertaskmanager
  sql:
    init:
      mode: embedded
  graphql:
    path: /graphql
    schema:
      default-schema-location: classpath:graphql/schema.graphqls
    graphiql:
      enabled: true
    execution:
      introspection-enabled: true


  datasource:
    url: jdbc:postgresql://localhost:5432/utm
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework: DEBUG
    com.bos.usertaskmanager: DEBUG
    graphql: DEBUG
    org.mybatis.spring: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.bos.usertaskmanager.model
  configuration:
    map-underscore-to-camel-case: true

admin:
  username: admin
  password: admin

utmd-agent:
  ip-port-list: # List of IP and port of all UTMD agents(Same as login server now, but should be compute nodes IP in future)
    - 192.128.20.241:8000
    - 192.128.1.104:8000
    - 192.128.1.106:8000
    - 192.128.1.107:8000
    - 192.128.1.108:8000
